[package]
name = "raytraced-weekend"
version = "0.1.0"
authors = ["Notnaton <4324290+Notnaton@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"